inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
   Enabled: false

Bundler/OrderedGems:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes

Style/GuardClause:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/password_resets_controller.rb'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'test/test_helper.rb'

AllCops:
  Exclude:
    - vendor/**/*
    - 'bin/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
  Rails:
    Enabled: true
